# Permalinks
permalink:           pretty

# Setup
title:            Whack Data
tagline:          Ryan Brideau
url:              http://www.whackdata.com
paginate:         1
paginate_path: page/:num
defaults:
  - scope:
      path: "page"
    values:
      sitemap: false
basename:         ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:           Ryan Brideau
  url:            https://twitter.com/Brideau
  email:          ryan dot brideau at google mail

twitter:
  username:       Brideau

social:
  name: Ryan Brideau
  links:
    - https://twitter.com/Brideau
    - https://ca.linkedin.com/in/ryanbrideau
    - https://github.com/Brideau
    - https://keybase.io/Brideau

# Custom vars
version:             2.1.0
github:
  repo:              https://github.com/poole/poole

# Tags
tag_feed_layout: tag_feed
tag_feed_dir: tag
tag_page_layout: tag_page
tag_page_dir: tag

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

pages_list:
  About: '/about'
  Archive: '/archive'
  RSS: '/atom.xml'