# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            Whack Data
tagline:          Ryan Brideau
url:              http://www.whackdata.com
paginate:         1
basename:         ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

# About/contact
author:
  name:           Ryan Brideau
  url:            https://twitter.com/Brideau
  email:          ryan dot brideau at google mail

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/poole/poole
