# Dependencies

markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            Whack Data
tagline:          Ryan Brideau
url:              http://www.whackdata.com
baseurl:          /
author:
  name:           Ryan Brideau
  url:            https://twitter.com/Brideau
  email:          ryan dot brideau at google mail
paginate:         1

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/poole/poole
