# Dependencies

markdown:         redcarpet
highlighter:      rouge
plugins:          [jekyll-paginate]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Whack Data
tagline:          Ryan Brideau
url:              http://www.whackdata.com
baseurl:          /
author:
  name:           Ryan Brideau
  url:            https://twitter.com/Brideau
  email:          ryan dot brideau at google mail
paginate:         1

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/brideau
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
